### ISSUE TITLE
Function name bug

### ISSUE THREAD

**Issue by franchesoni** [haruishi43/py-edge-eval#2]
https://github.com/haruishi43/py-edge-eval/blob/f1706c601dc8ca3744cffcfa85c9ba8596a79755/pyEdgeEval/helpers/evaluate_bsds500.py#L146-L162

The code above should be calling `evaluate` and not `evaluate_bsds500` (would break otherwise)

**Comment by haruishi43** [comment]
Good catch, thanks! Fixed
